### ISSUE TITLE
package構成の変更について

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#10]
#9 で行われたミーティングで決まったことについて
- [x] `cirkit_unit03` -> `cirkit_unit03_common` ( @forno )
- [x] `cirkit_unit03` から `cirkit_unit03_navigation`を切り出す。 ( @MoriKen254 )
- [x] navigationでgazeboと実機でpkgを分けないで、configの中でディレクトリを分ける ( @MoriKen254 )
- [x] `cirkit_unit03_pkgs` を作る ( @RyodoTanaka )
- [x] `cirkit_unit03_apps` を作る ( @RyodoTanaka )
- [x] `waypoint_manager`からmsgだけを切り出した`waypoint_manager_msgs`を作る ( @Ariyu )

**Comment by AriYu** [comment]
がんばりましょう :exclamation: :+1:

**Comment by forno** [comment]
cirkit_unit03 リポジトリを cirkit_unit03_common リポジトリにリネームしました。
問題がないか確認してください。
なお、リネームの挙動として、リネーム元の名前でもリポジトリにアクセスできるという特徴がありますので皆様お手元のリポジトリのremote repositoryを新しいリポジトリ名に変える必要性は無いかと思います。

**Comment by AriYu** [comment]
> `waypoint_manager`からmsgだけを切り出した`waypoint_manager_msgs`を作る ( @Ariyu )

は https://github.com/CIR-KIT/waypoint_manager/pull/19 と https://github.com/CIR-KIT/waypoint_manager_msgs/pull/1 で対応しました。

**Comment by MoriKen254** [comment]
2点あります．

### 1点目

> `cirkit_unit03` から `cirkit_unit03_navigation` を切り出す

についてですが，`cirkit_unit03_navigation` をmetapackageとして，その配下に下記のようなpkgを作るのでよかったですか？
- `cirkit_unit03_move_base`
- `cirkit_unit03_gmapping`
- `cirkit_unit03_amcl`

### 2点目

>  navigationでgazeboと実機でpkgを分けないで、configの中でディレクトリを分ける

ですが，

> cirkit_unit03_apps を作る ( @RyodoTanaka )

のpkgにlaunchを置いて検証できたらと思っています．

お手すきの時で良いので，@RyodoTanaka さんの想定しているであろうフォルダ構成で，`pkg`だけ作ってもらえるとありがたいです^^
場所だけもらえると助かるので，ひとまずrosinstall 無しで大丈夫です．

**Comment by AriYu** [comment]
@MoriKen254 
1点目に関してはそれで良いと思います。

**Comment by MoriKen254** [comment]
2点目について．

`CIR-KIT-Unit03`に，`cirkit_unit03_apps`というリポジトリを作成し，`cirkit_unit03_apps`という`pkg`を作るという認識でよろしいでしょうか？

問題がない，あるいは11/22(火) 09:00 まで連絡がなければ，とりあえずその構成で作成して，当方の作業を進めたいと思います．

申し訳ございませんが，ご了承よろしくお願いいたします．

**Comment by RyodoTanaka** [comment]
@MoriKen254 @AriYu @forno 
反応鈍くて申し訳ありません．
今からpackageの統合作業を開始します．
よろしくお願いします．

**Comment by MoriKen254** [comment]
このときの目標は達成したと思うので，閉じます．
