### ISSUE TITLE
msgs packages の置き場所とか

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#11]
三号機固有のメッセージは無いでしょうから、ここに書くのも何ですが。

`common_msgs` だけに依存しているmsgs専用のリポジトリ (それこそ common_msgsに相当するようなmsgs用メタパッケージ) があれば、それを呼ぶだけでCIR-KIT のパッケージのうち、トピック通信を採用しているものを簡単に利用できるようになるかと思い提案させていただきます。

**Comment by forno** [comment]
https://github.com/CIR-KIT/waypoint_manager/issues/14
との差別点としては、メッセージ専用のリポジトリを作りませんかという提案となっている点です。

**Comment by MoriKen254** [comment]
そうですね，別リポジトリにするのが良いと思います．

`CIR-KIT/common_msgs` ですかね．

**Comment by AriYu** [comment]
あ、waypoint_managerも別リポジトリにするつもりでした。

**Comment by AriYu** [comment]
使う必要がでてきたらそうしましょう。
