### ISSUE TITLE
相談(決めごと)Issue と リポジトリ変更を伴うIssue の取り扱い

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#12]
Issueには相談事(決めごと)のものとリポジトリの内容変更を伴うものがあるかと思います。

約束事のIssueは結論が出たら閉じるべきかと思いますが、変更を伴うものについての取り扱いについて決めておいたほうが良いかと思いこのIssueを開きます。

今までは、なんとなく変更を伴うものについても方針が決まったら閉じるようにしていました。
内容が確定した時点で議論が終了したことをわかりやすくするためです。　なにか不都合が生じれば再び開くこともでき、これはこれで分かりやすかったと思います。

最近知ったのですが、コミットメッセージからIssueを操作できるようです。[Github help](https://help.github.com/articles/closing-issues-via-commit-messages/)
これを使えば、対応するPull-request(正確にはコミット)がデフォルトブランチにマージされた時点でIssueを閉じることができます。
その場合は、Issueに対応した変更が適用された時点で自動的に閉じられ、Issueの議論が正しくデフォルトブランチに適用されたことを示せるかと思います。つまり、閉じられていないIssueはまだデフォルトブランチに作業が適用されていないことを意味します。

どちらの戦略も良い所があり議論の余地ありと判断しました。ご意見お待ちしています。

**Comment by AriYu** [comment]
なんかタグを作りますか？
あとで修正プルリクを送るつもりがあれば何かしらのタグを付けるようにして区別するのはどうでしょう。

**Comment by MoriKen254** [comment]
> コミットメッセージからIssueを操作できる
> あとで修正プルリクを送るつもりがあれば何かしらのタグを付けるようにして区別する

両者は共存可能と思います．
前者は閉じ忘れの防止，後者はissueリストでの一覧性の向上に寄与するでしょう．

タグについては，`pull-requesting`くらいの名前で登録しましょうか？

**Comment by forno** [comment]
そうですね。
プルリクエストを要求することが見えてきた段階で特別なタグをつけるのがわかりやすい上、識別しやすいと思います。途中からつけたり外したりできる点が特に良いと思います。

> タグについては，pull-requestingくらいの名前で登録しましょうか？

ラベル名にpull-requestを入れるのは、少々悩みましたが、ラベルの意味を知らない人が見てもわかりやすくて良いと思います。 `pull-requesting` に賛成します。

**Comment by MoriKen254** [comment]
ありがとうございます。異論が無ければ、`pull-requesting`タグを追加します。

**Comment by AriYu** [comment]
作ってみました。
どうでしょう？

**Comment by forno** [comment]
警告色でちょっぴり痛い色合いですね。被り色はなかったと思うので良いと思います。

**Comment by AriYu** [comment]
被ってない色で明るい色を選びましたが、他の色にしてみますか？

2016年11月21日(月) 22:56 Doi Yusuke notifications@github.com:

**Comment by forno** [comment]
デフォ色だと黄色かオレンジか紫くらいしか残ってなさそうですね。

pull-requestingが付くならAssignee'sも大抵はついていて、直ぐに対応するPull-requestも(とりあえず開くだけでも)開かれてるんじゃないかなと考えると、もう少し目立たない色でも良いかなと思います。

一番右の紫(のような青のような)色は如何でしょうか。

**Comment by MoriKen254** [comment]
ありがとうございます．

では，紫にしましょうか．一覧から認識できれば良いと思います^^

**Comment by forno** [comment]
とりあえず変えてみました。自分が思ったよりも青に被ってる気もします。

まあ、目立って困るかと言うと特にそうでも無いので、視認性や個人の都合で良い方を選んでくださいまし。

**Comment by AriYu** [comment]
ではこれでいきましょう。

**Comment by forno** [comment]
ではこの紫色にてpull-requestingラベルを運用してみましょう。

全部につけて回るのも大変でしょうし、一先ず必要になった時にラベルがなければ自作する感じでよろしくお願いします。
暇があればラベルを作って回っても良いですが、優先度は低いです。
