### ISSUE TITLE
Repository プロテクト強化のお誘い2

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#15]
Travisの導入が順調に進んでいます。

そこで再度リポジトリプロテクトの強化のお誘いです。
今回はTravisのテストに通らないとマージできないというプロテクトです。
効果は大体Approveの時と同様です。そして、Adminまわりの話も同様です。

ただ、Travisのテストは、テストをきちんと整備して初めて役立つものです。
Travisの制限は過信し過ぎず、レビュとApproveを大切にしてゆきましょう。

導入についての意見をお待ちしております。

**Comment by AriYu** [comment]
@forno 
travis通らなくてもマージしていいとは思いますがどうでしょうか。
というもtravisを通すのに非常に手間がかかる場合があるからです。
もちろんテストを書いて通すのがベストだと思います。

**Comment by forno** [comment]
Travisでは catkin_make test と catkin_make run_tests を行っているだけのはずですが、
それは何気に通らないものなのでしょうか。

**Comment by AriYu** [comment]
catkin_makeが通すことが難しい時があるという感じですね。
Travisをマージの条件にするのはすべてのリポジトリで通ってからでもいいと思います。

2016年11月18日(金) 22:33 Doi Yusuke notifications@github.com:

**Comment by forno** [comment]
@AriYu 
なるほど。安定していそうなところから順次かけていこうとおもっていましたが、確かに何処で何に影響が及ぶかまだ現段階で判断するのは早そうですね。
では、パッケージの移動が終わるまでは完全に保留。
それからまた考えるということで良いでしょうか。

**Comment by MoriKen254** [comment]
> では、パッケージの移動が終わるまでは完全に保留。
> それからまた考えるということで良いでしょうか。

本意見に賛成です．将来的にきちんと動くものができたら導入という形で．

> Adminまわりの話も同様です。

本番前の急ぎの時にすぐマージできるように変更可能なら，安心です．

**Comment by forno** [comment]
それではwhole issue見通しのため一旦閉じます。
時期が来ればまた開きましょう
