### ISSUE TITLE
コーディング規約について

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#16]
※本内容はUnit03を超えた`CIR-KIT`全体での内容になるのでココに立てたくは無かったのですが、`CIR-KIT`側に`whole issue`に相当するリポジトリが無かったので、とりあえずこちらに立てます。

チーム内で最低限守るルールを明文化できればと思っています。

おそらくこれは`whole_issue`の`Code`内にルールを記載した`README`を配置し、各自参照してコードを書く、と言う形にできれば、分かりやすくなるかなと思います。

何か参考にしているリンクとかあれば、まずは共有しませんか？よろしくお願い致します。

追記：`README`を配置するのは、`CIR-KIT`organization 配下の然るべきリポジトリにすべきかと思います。`Wiki`もありかと思います。より皆が使いやすい方法で共有したいですね。

**Comment by forno** [comment]
現在の私のコーディングの参照先は 「プログラミング言語C++ 第4版」(ビャーネ・ストラウストラップ　柴田望洋 訳) という本ですね。とはいえこの本はコーディング規約書ではないです。

また、最も影響を受けているのがEffective c++系列の本です。第三版, More, Modernにかかれていた内容とその書き方に一致するものがあればそのように書くようにしています。 この本たちもコーディング規約書では無いです。

コードの命名とかで私が悩んだ時に参照することが多かったのは [Googleのc++ スタイルガイド](http://www.textdrop.net/google-styleguide-ja/cppguide.xml) です。主にはここから例外を許可したものをベースにしています。 とはいれこれもコーディングというよりは、使って良い物、悪いもの、使い方、使われ方をベースに命名則の集まりと言った体ではあるかと思います。

最終的に、私のコーディングの真の基本となっているのはなんと言ってもJavaのコーディング則です。
[永和システムマネジメントさんのJavaコーディング標準](http://objectclub.jp/community/codingstandard/CodingStd.pdf)をベースとした記法を主に採用しています。この資料には if文, while文と言ったレベルでのコーディング則が `5. ガイドライン (28) コーディングスタイル` にまとめられており、基本的な文法を統一するのに向いている上、読みやすく理解しやすい資料となっていると思います。

c++ のコーディング方法は調べても古い情報、新しい情報、古い戦略、新しい戦略が混ざっておりなかなかこれ！という書き方は見つかりません。 独断と偏見ですが、比較的新しいC++の本では現在のJavaに近い記法が採用されており、それも相まってEffective C++の書き方を真似つつ、細かいコーディングは[永和システムマネージメントさんのJavaコーディング標準](http://objectclub.jp/community/codingstandard/CodingStd.pdf)に従ってコーディングしています。

さて、ここまで自分の話でしたので、プロジェクトのコードについての話に戻りますが、コードについては、初めにプロジェクトごとにコーディングスタイルを設定するのか、それともチーム全体で統一するのかという問題があるかと思います。

今回ではチーム全体に適用することを念頭にするようですので、その方針で考えるならば、コーディング規約をある程度の期間で更新するようにしたほうが良いかと思います。
C++は歴史も長く、かつ恐らくこれからも長く存在する言語ですので、今よい文法が明日も良いとは限らないかと思います。

最後に私のコーディングの適用について軽くまとめておきます。
私のコーディング規約も正確には明文化していないのであれですが、
1. 記法について: [永和システムマネージメントさんのJavaコーディング標準](http://objectclub.jp/community/codingstandard/CodingStd.pdf) の記法に基づいている。 
2. 命名則について: [Goggleのc++ スタイルガイド](http://www.textdrop.net/google-styleguide-ja/cppguide.xml) の命名則に基づいている。ただし記法は 1. を参照する。
3. ソフトウェアパターンについて: Effective C++ 系の本(3種)にて示されるアンチパターンの回避と推奨的パターンの適用
4. C++でできることについて: プログラミング言語C++ 第4版 (ビャーネ・ストラウストラップ　柴田望洋 訳) を参照する

**Comment by MoriKen254** [comment]
素晴らしいですね！！！ありがとうございます．
リファクタリングもしてくださっていますし，是非 @forno さんの方針，情報を参考にしたいです．

チームで規約を設けようと思ったのは，`CIR-KIT`の皆さんで統一できるようにしたいという思いがありました．確かに定期的な更新は必要になるかもしれませんね．それは今後のサークルのメンバーに託すという形になりますね．

そういう運用を考慮する上でも，チーム全員が守るべきルルールは，ある程度絞れたらな，と思っています．ルールが煩雑になると管理が難しくなったり，メンテナンスの負担の方が大きくなったりする可能性もあるためです．

例えば，スタイルと命名則こ限った場合，この記事くらいのボリュームなら，スリムかな，と思います．
http://qiita.com/shirakawa4756/items/55b509fb56cb1bb0c9a4

もちろん，プロジェクト単位，ひいては個人単位で更にブラッシュアップするのは，私は大歓迎と思います．

ということを踏まえ，こういう方針は如何でしょうか．

- チーム全体で守るべきルールは，ざっと閲覧できる分量に絞って，明文化する．
- 個人単位で更なるブラッシュアップすることは推奨する．
- ルールとはしないまで守ると美味しい情報は，Tipsとしてルールとは別の場所で共有したり，参考文献を掲載したりする．

どこまでルール化するかの線引が難しいかもしれませんが，エイヤで決めてしまって問題があれば修正すればいいかなと思っています．

**Comment by AriYu** [comment]
@MoriKen254 @forno 
最近はこれを見ながら整形しています。
http://wiki.ros.org/CppStyleGuide
そこまで文量は多くないので守るのは難しくないかと思います。
ただ、`CMakeLists.txt`や`.launch`のフォーマットなどが示されていないので、その辺は統一したいです。

あとコーディングに関しては、リーダブルコードを参考にしています。

**Comment by AriYu** [comment]
個人的にはROSのスタイルガイドに従いたいとは思っています。

**Comment by forno** [comment]
なるほど。ROS の StyleGuide ですね。
前にも見たことがあったような気はしますが、存在を忘れておりました。

これを全員に通達するのはとても簡単で良い案と思います。

このようなコーディング規約のifとかの`{` への言及は割と多いですが `(` のほうが無いので、`if`とか`while` と `(` の間にスペースを入れてくれるようにしてくだされば私的に見やすくて助かります。基本的に自主性に任されていると解釈するところですが、木村教授が関数呼び出しと区別しやすいとおっしゃられたことが有り、なるほどと思ったことがあります。

とりあえず私の今後のROSのソースコードに前述のスタイルは反映してゆきます。

**Comment by AriYu** [comment]
@forno 
http://wiki.ros.org/CppStyleGuide#Formatting のlarger exampleを見ればifやswichと`(`の間にはスペースがあるので良いと思います。

**Comment by forno** [comment]
@AriYu 
久しぶりに読みましたが、結構内容も変化しているものですね。
私が知っている段階のものとはまた結構違うようです。

日本語版なんてまるっきり更新されてませんので、通達するなら英語の方を読むようにしっかり伝えて、定期的に読むように通達したほうがよいかもしれませんね。

**Comment by MoriKen254** [comment]
活発なご意見有難うございます．

では，基本的に http://wiki.ros.org/CppStyleGuide に従うようにしましょうか．
ROSでなくても使えるエッセンスになっていると思います．

もしこのスタイルで問題が出たら，またその時話しましょうか．

どこかに明記しておきましょうか．`CIR-KIT`配下にも`whole-issue`的なリポジトリを作って，サークル全体のルールを管理するというのはいかがでしょうか．

**Comment by AriYu** [comment]
READMEに書いておきましょう

**Comment by MoriKen254** [comment]
https://github.com/CIR-KIT/WholeIssue にまとめました．
