### ISSUE TITLE
package.xml の export タグの正しい使い方を教えてください

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#18]
今までデフォルトで存在し、なんの害も及ぼさなかったのでexportについてろくに調べず放置していました。
私の知識ではメタパッケージを作る際に必要だ、と言うことくらいの事しか知りません。

しかし、このexportタグを消しても正しく動きますし、catkin の overview にも指定が無いので、中身がなければ書かなくてもいいのでは無いかと思っています。 昔、一時期削除していた時期も有り、その際もなんの問題もなく稼働していた経歴も有ります。

正直なところ、空の`export` を残しているROS core stacks さんのパッケージは無いです。[参考: actionlib](https://github.com/ros/actionlib/blob/indigo-devel/package.xml)

ただ、英語は苦手なので、デフォルトで有効になっていることも有り、日和って削除をためらっていただけなのです。
不必要なものなのであれば、この機会に削除してしまいたいと思います。

ただし、単に`msg`などの生成だけを行っているパッケージには最適化が施せるとかいろいろ書いてあるのでそういうのにもいつか手を出せたら良いなと思います。

ご意見お待ちしております。

参考資料:
- http://docs.ros.org/kinetic/api/catkin/html/howto/format2/catkin_overview.html
- http://www.ros.org/reps/rep-0140.html#export
- [geometry_msgs (export最適化有り)](https://github.com/ros/common_msgs/blob/jade-devel/geometry_msgs/package.xml)
- [xacro (export最適化有り)](https://github.com/ros/xacro/blob/kinetic-devel/package.xml)
- [robot_state_publisher (export無し)](https://github.com/ros/robot_state_publisher/blob/kinetic-devel/package.xml)

**Comment by AriYu** [comment]
@forno 
`export`タグはpluginを作った時に使った覚えがありますが、他には使ってないと思います。
使わない時は消して良いと思います。
