### ISSUE TITLE
全体のソフトウェア構成の修正について

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#19]
本件，独立してissueを立てます．

https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/10 の一環で，gazebo側の構成を下記のように修正しました．

- 赤：リポジトリ名
- 青：パッケージ名
- 緑：呼び出しnode名
- `cirkit_unit03`は省略．

![software_config](https://cloud.githubusercontent.com/assets/12078261/20592195/86f44e2c-b26f-11e6-9c88-102e0bcca07b.png)

この構成でよいでしょうか？

もしOKなら，実機側も同様の構成になるよう修正してもらえますか？
もし修正の途中で，もっとGazebo側と共通化できるファイル等あれば，issueにあげてください．

**Comment by AriYu** [comment]
@MoriKen254 
分かりました。
やってみます。

**Comment by AriYu** [comment]
@MoriKen254 
ただ、実機は`Robot::HW`の実装ができていなので、その辺りはまだ統一できません。

**Comment by MoriKen254** [comment]
reference されたpull-requestがマージされたら閉じることとします．

**Comment by forno** [comment]
すべてMergeされたようですね

**Comment by MoriKen254** [comment]
すべてマージされたので、閉じます。
