### ISSUE TITLE
ミーティング

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#20]
突然ですみません．今週分の進捗確認のミーティングの時間を頂けませんか？

11/25(金) 17:00 頃 学生室集合

で，ご都合いかがでしょうか．

@AriYu 
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/19 の実機側のソフト構成の見直しについて，やれそうですか？

@RyodoTanaka 
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/10 のチェックボックスを何とか埋めてもらえませんか？
リポジトリを作って.rosinstallの設定を書けばOKと認識しています．

あと，今週でlaunchテストを通しておきたいので，色々教えて頂ければ幸いです．

**Comment by AriYu** [comment]
@MoriKen254 
承知しました。
やってみます。

**Comment by forno** [comment]
@MoriKen254 
そのミーティングには私も参加してもよろしいでしょうか。

**Comment by MoriKen254** [comment]
いらしていただけるなら是非！

お忙しいと思いますが、よろしくお願いします。

**Comment by AriYu** [comment]
launchテストを通す対象
- [x] cirkit_unit03_apps ( @MoriKen254 )
- [x] cirkit_unit03_navigation ( @Ariyu )
- [x] cirkit_unit03_robot ( @Ariyu )
- [x] cirkit_unit03_common ( @Ariyu )
- [x] cirkit_unit03_simulator ( @MoriKen254 )
- [x] cirkit_unit03_desktop ( @forno )

**Comment by AriYu** [comment]
- [x] `map_server`は独立させる
- [x] mapsのnavigation配下にpkgを作る

**Comment by AriYu** [comment]
- [x] `human_detector`を移す
- [ ] つくばチャレンジのレポートを書く
  * [x] 2015の文書を移動する
  * [ ] 2016の文書を書く

**Comment by AriYu** [comment]
- [x] `gmapping`の`description.launch`を呼び出す際にarg要らない

**Comment by AriYu** [comment]
- [x] `third_robot_lower_step_detector`は`control`に移動する

**Comment by AriYu** [comment]
- [ ] information系はREADMEに移動するか、リンクを貼る

**Comment by AriYu** [comment]
大体、片付けたので閉じます。
