### ISSUE TITLE
cirkit_unit03_desktopは不必要ではありませんか？

### ISSUE THREAD

**Issue by RyodoTanaka** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#21]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_desktop/issues/7 にて問題提起しています．
同様にここにも記します．

`cirkit_unit03_desktop`では、
- Rvizのconfigulationファイルを保持
- Robot description 単体でRviz上での起動を確認

する機能がサポートされていますが、これらは不必要、つまりcirkit_unit03_desktop`リポジトリ自体が不必要に感じます．
というのも、
- RvizのConfigulationファイルは，それ必要とする各パッケージで保持したほうが良い
- Robot description 単体でRviz上での起動確認は`cirkit_unit03_description`上で行ったほうが良い

と考えるためです．

また、[PR2](https://github.com/PR2?utf8=%E2%9C%93&q=&type=&language=)、[Husky](https://github.com/husky)、[turtlebot](https://github.com/turtlebot?utf8=%E2%9C%93&q=&type=&language=)、[baxter](https://github.com/RethinkRobotics?utf8=%E2%9C%93&q=&type=&language=)を確認しましたが、本リポジトリのようなものを保持しているのはHuskyのみでした。
以上を踏まえた上で、やはり`cirkit_unit03_desktop`は不必要に感じますがいかがでしょうか？

**Comment by MoriKen254** [comment]
そうですね，`description`にまとめることに，私は賛成です．リポジトリも減って管理しやすいかと．

ついでに，https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/tree/master/cirkit_unit03_description/launch 内のファイルは，`description.launch` 以外は消してしまっても良さそうですね．

**Comment by RyodoTanaka** [comment]
@MoriKen254 
早速のお返事ありがとうございます．
1. `cirkit_unit03_desktop`へ依存しているパッケージを無くす
2. 了承が取れ次第、`cirkit_unit03_desktop`を削除する

以上の手順で作業を進めたいと思います．

**Comment by RyodoTanaka** [comment]
@AriYu @forno 
本issueの`cirkit_unit03_desktop`の削除について賛否をお聞かせください．
よろしくお願いします．

**Comment by forno** [comment]
~~コントリビューションが減ってしまうのが悲しい以外は~~ 大丈夫です。

**Comment by RyodoTanaka** [comment]
@MoriKen254 @AriYu @forno 
第１段階として、`cirkit_unit03_description` -> `cirkit_unit03_viz`の依存を解消しました．
https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/pull/25 にてPRを投げているので認証をおねがいします．

**Comment by AriYu** [comment]
:ok_man:

**Comment by RyodoTanaka** [comment]
@MoriKen254 @AriYu @forno 
皆様、了承ありがとうございます．
`cirkit_unit03_desktop`の削除については、https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/issues/26 で議論されているように、
1. `cirkit_unit03_viz`に保持されている内容を他のパッケージに移動させる。
2. `cirkit_unit03_desktop`を削除する

という手順で行いたいと思います．本issueは、`cirkit_unit03_desktop`の削除後に閉じます．
よろしくお願いします．

**Comment by RyodoTanaka** [comment]
`cirkit_unit03_desktop`の削除が完了しました．
ご協力ありがとうございました．
