### ISSUE TITLE
ミーティング 16/12/08(木)

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#24]
前回は突然の来校に関わらず、対応いただき本当にありがとうございます。

少し休憩挟めたと思うので、一回ミーティングしましょうか ^^

- 12/8 (木) 14:00

下記issueの進捗、方針等確認。
- https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/22 

お時間よろしければ、よろしくお願いします。

**Comment by AriYu** [comment]
@MoriKen254 
16時ごろまでしか対応出来ませんが、よろしくお願いします。

**Comment by MoriKen254** [comment]
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/25 に移したので閉じます．
