### ISSUE TITLE
Pull Request 残件 12/19

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#28]
お騒がせしております．12/19時点で下記プルリクエストが残っています．

ドキュメントを追加するのにまたブランチを追加することを考えるとプルリク数が倍になるので，一旦マージしたほうが管理がしやすくなるかな，と思っています．

Approve をお願いいたします :bowing_man: 

- [x] https://github.com/CIR-KIT/waypoint_manager/pull/22
- [x] https://github.com/CIR-KIT/steer_drive_ros/pull/14
- [x] https://github.com/CIR-KIT/steer_drive_ros/pull/15
- [ ] https://github.com/CIR-KIT/steer_drive_ros/pull/16
- [x] https://github.com/CIR-KIT/human_detector/pull/4
- [x] https://github.com/CIR-KIT-Unit03/cirkit_unit03_simulator

下記は，動作確認方向を受けたらApprove します．

- [x] https://github.com/CIR-KIT-Unit03/cirkit_unit03_robot

**Comment by MoriKen254** [comment]
kinetic と jade の動作確認が出来たら，本家にプルリクを出そうと思います ^^

問題があれば，教えてください．

**Comment by AriYu** [comment]
@MoriKen254 
kinetic環境ですがROS＆gazeboのセットアップまでは出来ていますので、できれば本日中になんとかしたいと思います。

**Comment by AriYu** [comment]
@Moriken254
申し訳ありません。
本日は出来そうにありません。
もしよろしれば明日までお待ちいただけないでしょうか？

**Comment by MoriKen254** [comment]
@AriYu 
:+1: :smiley:

**Comment by AriYu** [comment]
@MoriKen254 
`steer_drive_ros`ですが、kinetic環境で`catkin_make`は通りました。
しかし、`gazebo`を起動しようとしたところ以下のようなエラーが出ました。
```
$ roslaunch cirkit_unit03_gazebo cirkit_unit03_clearpath_playpen.launch 
... logging to /home/nishidalab/.ros/log/d8fa0042-ccd5-11e6-8cfa-704d7b6a93c5/roslaunch-NEDO02-17722.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
inconsistent namespace redefinitions for xmlns:xacro:
 old: http://ros.org/wiki/xacro
 new: http://www.ros.org/wiki/xacro (/home/nishidalab/ROS/cirkitunit03_ws/src/cirkit_unit03_pkgs/cirkit_unit03_common/cirkit_unit03_description/urdf/cirkit_unit03.xacro)
unknown macro name: xacro:cirkit_unit03_robot
XacroException(u'unknown macro name: xacro:cirkit_unit03_robot',)
when processing file: /home/nishidalab/ROS/cirkitunit03_ws/src/cirkit_unit03_pkgs/cirkit_unit03_simulator/cirkit_unit03_gazebo/urdf/description.gazebo.xacro
while processing /home/nishidalab/ROS/cirkitunit03_ws/src/cirkit_unit03_pkgs/cirkit_unit03_simulator/cirkit_unit03_gazebo/launch/description.gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py '/home/nishidalab/ROS/cirkitunit03_ws/src/cirkit_unit03_pkgs/cirkit_unit03_simulator/cirkit_unit03_gazebo/urdf/description.gazebo.xacro'] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find cirkit_unit03_gazebo)/urdf/description.gazebo.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file
```

**Comment by AriYu** [comment]
@MoriKen254 
もちろん、`steer_drive_controller`の実行もできます。セグフォなどは起こしません。
```
roslaunch cirkit_unit03_control control_gazebo.launch
```
ただし、gazebo側が上記の問題により起動できていないので動作確認はまだです。

**Comment by AriYu** [comment]
@MoriKen254 
[ `cirkit_unit03_simulator/cirkit_unit03_gazebo/urdf/description.gazebo.xacro`の15~17行目 ]( https://github.com/CIR-KIT-Unit03/cirkit_unit03_simulator/blob/master/cirkit_unit03_gazebo/urdf/description.gazebo.xacro#L15-L17 ) をコメントアウトしたところ、エラーは起きなくなりました。

また、一通り動作することを確認しました。
ただし、おそらく`cirkit_unit03`固有の問題だと思いますが、gazebo上だとかなりスリップしてしまうようです。まとも制御できません。
https://youtu.be/RFC9wJM_1GU

遅くなってしまいすいません、検証できるのはここまでです。
以上、よろしくお願いします。

**Comment by MoriKen254** [comment]
@AriYu 
ありがとう！

コメントアウト部，simulatorリポジトリでkinetic-develでも作成してこちらで消したものを上げておきます．
xacroのwarningについても，ROSのヴァージョンアップに伴う既知の仕様変更点ですね．後で直しておきます．

YouTubeのリンクで「この動画は再生できません」と表示され確認できないのですが，何となく想像がつきました．URDF側の摩擦パラメータの設定なのかもしれませんね．(バージョン間で変更が必要なのかと疑問符はつきますが^^;)

念のため，

```
roslaunch cirkit_unit03_gazebo cirkit_unit03_world.launch
```

も確認してもらえますか？これでも滑るならロボット側のパラメータの問題になり，これでは滑らないならworld側のパラメータの問題になる，くらいの切り分けはできるかなと思います．

**Comment by AriYu** [comment]
@Moriken254

すいません。ビデオの設定を修正しました。

そうですね、空のワールドでも試してみておくべきでした。

勝手ながら帰省しておりまして、申し訳無いのですが、1週間ほどはちょっと難しいです。

誰か研究室にいる人に頼むことが出来れば良いですが…

2016年12月28日(水) 21:10 Masaru Morita <notifications@github.com>:

**Comment by MoriKen254** [comment]
@AriYu 

お休みのところの返信，ありがとう．

うーん，前輪の車軸がダメダメですね笑．後輪はちゃんと地面と摩擦しているようなので，おそらく見立通りモデルの問題でしょうね．

こちらの問題が解決しないと先方にexampleを提示できないので，プルリクは年明けに出すことにしましょう．

実家でゆっくり休養して下さい♪良いお年を！
