### ISSUE TITLE
third_robot_pkgからの移行進捗

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#4]
- ~~scripts~~ 	
- [x] steer_bot_hardware_gazebo 	
- [x] step_back_and_max_steer_recovery 	
- [x] third_robot_2dnav 	
- [x] third_robot_2dnav_gazebo 	
- ~~third_robot_avoidance_limiter~~ 	
- [x] third_robot_bringup 	
- ~~third_robot_chess_recognize~~ 	
- [x] third_robot_control/steer_drive_controller 
- [x] third_robot_description 	
- [x] third_robot_driver 	
- [x] third_robot_gazebo 	
- [x] third_robot_gmapping 	
- [x] third_robot_gmapping_gazebo 	
- [x] third_robot_lower_step_detector 	
- [x] third_robot_merge_laser 	
- [x] third_robot_monitor 	
- ~~third_robot_nav_goals~~ 	
- ~~third_robot_offset_urg~~ 	
- ~~third_robot_sound~~ 	
- ~~third_robot_talker~~ 	
- [x] third_robot_urg_filter

**Comment by RyodoTanaka** [comment]
@AriYu 
`third_robot_merge_laser`はどこに移行されたのか教えてください。

**Comment by AriYu** [comment]
@RyodoTanaka 
以下に移動しました。
https://github.com/CIR-KIT-Unit03/cirkit_unit03_common/tree/master/cirkit_unit03_control/launch

**Comment by MoriKen254** [comment]
これは移行完了という認識でOKですか？

**Comment by AriYu** [comment]
@MoriKen254 
そうですね。
閉じます。
