### ISSUE TITLE
package.xml につけるauthorタグについて

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#5]
authorタグには我らの団体名を使うべきかと思うのですが、
CIR-KITにするべきか、CIR-KIT-Unit03にすべきかわかりかねましたので、Issueを開かせていただきます。

また、authorタグに他の記入をする例もあるので、一概にその方法が良いとは言えません。
他の記入とは例えば、主要な開発者を羅列する等です。

他のご意見もありましたら書いてくださると大変助かります。
すでに明確な方針が決まっていましたら教えていただけると有り難いです。

**Comment by MoriKen254** [comment]
現状明確な指針はありません。

私は一般的な方法を取った方が良いと思います。それが団体名という理解でよろしいでしょうか。

団体名なら、サークルであるCIR-KITにすべきと思います。

いかがでしょうか。

**Comment by forno** [comment]
調べた限りだと個人名を羅列するパターンのほうが圧倒的に多いかと存じます。
大本の[catkin](https://github.com/ros/catkin/blob/kinetic-devel/package.xml)や[pr2_common](https://github.com/PR2/pr2_common/blob/indigo-devel/pr2_description/package.xml)、[husky](https://github.com/husky/husky/blob/indigo-devel/husky_description/package.xml)も個人名を書いているようです。

簡単に結論だけ言うなら、真の著作権者の名前を書くのが筋だと思います。

この点で、fifth_robot_pkgでは開発者の合意のもと著作権はCIR-KITに帰属させることとしていましたので、こちらでもそのように申させていただきました。
前置きもなく、団体名を使うのが良いという選択を押し付け申し訳ございません。

しかし、ここにあるパッケージに限らずCIR-KITに関係のあるパッケージの著作権が誰にあるのかという問題に対しては、個人的に申し上げてCIR-KITに帰属させるのがよいかと思っております。

我々が去った後、プログラムの保守、開発を行うのは次代のCIR-KITの者達ですが、その者たちが保守のために書き加えたコード部分だけにその人の著作権を示すのは難しいですし、かと言って原作者へ全部還元しろと暗に要求するのも好きではありません。
コードに一行でも追加したらとりあえずauthorに追加する案も際限なく数が増えそうで嫌です。

その点、CIR-KITを著作権者にしておけば後世も真に好き勝手に扱えますし、様々なライセンスが要求する著作権者の表示もCIR-KIT一人分書けば良いことになり、私がこっそり使用するときに大変助かります。

まあ、自分は自己主張が激しいので自分の名を書けるなら書きたいですが(笑)

**Comment by forno** [comment]
ちなみにですが、逆に maintainer タグには現在保守を行っている人の名前をきちんと書くことが大切だと思います。

**Comment by AriYu** [comment]
基本的には`CIR-KIT`にするのがいいと思いますが、個人の名前を残したいときは残してもいいと思います。
柔軟に対応すべきだと思います。

ただ、無制限にということにすると際限なく増えていくと思うので、オリジナルの独自のアルゴリズムを作った時とかですかねぇ。

**Comment by forno** [comment]
では基本的にCIR-KIT、必要に応じて個々人の名を足すということで良いでしょうか。

傍から見ると、外部協力者に見えそうではありますが(笑)

**Comment by MoriKen254** [comment]
当方もその方針で賛成です．

卒業すれば外部協力者となると思うので，まぁいいということにしましょうか笑．
のちのち問題が起きた時に，偉大なる先輩にお伺いできる，というのも悪い話ではなさそうです．

**Comment by forno** [comment]
それでは全パッケージのpackage.xmlに

``` xml
<author email="cirkit.infomation@gmail.com">CIR-KIT</author> 
```

を含める。ということで良いでしょうか。

また、これに合わせてLICENSE.txtの著作権保持者をCIR-KITにしたいと考えています。
これについてもご意見いただけますと幸いです。

**Comment by AriYu** [comment]
@forno 
良いと思います。

**Comment by forno** [comment]
それでは実際に運用されていることもあるので。

## LICENSE にはCIR-KITと表記
## package.xml のauthorをCIR-KITと表記

としてゆきましょう。
