### ISSUE TITLE
今更ですが LICENSE について

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#6]
HI.
現在、CIR-KIT-Unit03のパッケージは大抵がMITライセンスになっています。
それはそれで構わないのですが、個人的にはcatkin packageにはBSD3条項ライセンスを使いたいと思っています。

その理由の一つが [ROSのパッケージがほとんどBSD3条項ライセンス](http://docs.ros.org/diamondback/api/licenses.html) だからです。
それ自体はROS自体がBSD3条項ライセンスなので当たり前といえば当たり前かもしれません。しかし、ライセンスが統一してあると、使う側は複数のライセンスを覚える必要性が無いため利用性が大変向上します。

ライセンスは自分にとって最も都合が良い物を選べばいいので、MITライセンスが良いのであれば全く問題ありませんが、なんとなく選んでいるのであればこの移動に合わせてBSD3条項ライセンスに切り替えるのもありかなと思いIssueを立てさせていただきます。

何か理由があってMITライセンスにしていましたら、お手数ですが理由を教えていただけましたら助かります。

**Comment by AriYu** [comment]
@forno 
特に理由があったわけではありませんが、敷いて言えばMITのほうがライセンスが緩そうだったからです。
BSDでも問題があるわけでないので、BSDに変更でもいいと思います。

**Comment by MoriKen254** [comment]
私もBSDで良いと思います．残件としておきましょう．
