### ISSUE TITLE
いまさらですが、誰がマージするのかについて

### ISSUE THREAD

**Issue by AriYu** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#7]
今は適当にマージしている感じがありますが、最低でもプルリクエストを出した人以外でApproveがあって、プルリクエストとApproveした人以外がマージしたほうがいいと思いますが、いかがでしょうか。
build報告は誰でもwelcomで。
こうすると開発には最低でも3人が必要ということになってしまいますが。

**Comment by forno** [comment]
私はPull-requestを出した人がマージするのが良いのではないかと思っています。

まずPull-requestを出し、他の人がApproveし、Pull-requestを出した人がマージし、即座にマージ後の状態をチェックする。
という流れが良いかと思っております。
これでしたら開発に2人、ということになります。

追記：
Pull-request者がマージするのは、マージ後の状態チェック時に万一問題があった時、一番対応しやすいかと思うからです。
また、開発途中でレビュが欲しくなった時などの、たまに未完の状態で出すpull-requestが誤ってマージされるという問題を回避できます。

**Comment by MoriKen254** [comment]
なるほど，よく分かりました，
「Pull-requestを出した人がマージする」で，承知しました．

**Comment by forno** [comment]
ではPull-requestの方針は以下のように。

## Pull-requestを出した人がマージする

Issueを閉じます。
