### ISSUE TITLE
Repository のプロテクト強化のお誘い

### ISSUE THREAD

**Issue by forno** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#8]
恐らく、私達はmasterに一切直接コミットせず、ブランチを切って作業し、確実にPull-requestを出して、必ずApproveを受け、masterに取り込むという開発手法をとっています。

これを規約として行っていますが、現状Approveしなくても緑色のマージボタンが押しやすいように出現しています。

ですので、全てのリポジトリにforce pushプロテクトとApprove requireプロテクトを加えたいと考えています。
Approve requireを有効にすると以下の画像のようにApproveされていないPull-requestをマージできなくなります。
いかがでしょうか。

追記： わかりやすいよう適当な名前で〇〇プロテクトと読んでいますが、一般的な呼び名かどうかはしりません。
![screenshot from 2016-11-14 23-43-05](https://cloud.githubusercontent.com/assets/11057257/20268820/1dd98608-aac4-11e6-9077-72f5b8210f58.png)

**Comment by MoriKen254** [comment]
賛成です．仕組みで歯止めをかけるのは良い試みと思います．

**Comment by AriYu** [comment]
ちなみにこれ誰も査読してくれなかったらどうなるんでしょうか？

**Comment by forno** [comment]
Adminを含む全ての人がマージできない設定を行った場合、誰もマージを行うことはできません。
ただし、我々はAdminなのでブランチの保護を解除する権限を持っています。設定画面に赴き、保護を一部解除して取り込み、再びAdminを含む全ての人に保護を適用することができます。

あるいはAdminに強制マージ権限を残したままプロテクトをかけることもできます。その場合は赤色のMargeボタンが出現し、マージコミットを送信する際にはAdminを行使するチェックボックスにチェックを入れる必要があります。

しかし前述の通り保護そのものを解除できるAdminを持っているので、完全に保護しておくのが良いと思います。
保護を解除するときもAdmin強制マージを行使できるレベルまでとして、赤いボタンでマージしてもらって強制マージした旨記述してもらうようにするのが良いかと思います。

**Comment by AriYu** [comment]
@forno 
分かりました。
ありがとうございます。
ではその運用でいきましょう。

**Comment by forno** [comment]
CIR-KIT-Unit03のリポジトリ全てと
CIR-KITのwaypoint_maneger, remote_monitor, steer_drive_ros の3つに
forse push の禁止、 require Approve (include Admin)を追加しました。
