### ISSUE TITLE
ミーティング

### ISSUE THREAD

**Issue by MoriKen254** [CIR-KIT-Unit03/cirkit_unit03_whole_issue#9]
各位

いい感じに盛り上がってきましたね．一度皆でミーティングをしませんか？
当方は 11/17(木) or 11/19(土) に調整できそうです．

皆さんのご都合はいかがでしょうか？

@forno さん
場所は西田研でもよろしいですか？

**Comment by AriYu** [comment]
@MoriKen254 
ちなみに今週末は学祭です。

**Comment by forno** [comment]
@MoriKen254 
場所は問題ありません。正確には学生が研究を行っているところで良いのですね。
どちらも私の都合を開けることはできそうです。ただ、木曜であれば16:40頃から身が空くかと思います。

**Comment by MoriKen254** [comment]
では仮に下記のように決めます．特に異論がなければこれで行きます．

## 日程
- 日時: 11/17(木) 17:00~
- 集合場所: 西田研 学生室

## 議題

基本的には，
- 現在溜まっている問題の整理
- 実はまだ気になっていたことがあって，的なことの引き出し
- タスクの割り振り

です．

よろしくお願いします．
楽しくやりましょう^^

**Comment by AriYu** [comment]
#10 にやることを残しました。
